apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
spec:
  selector:
    app: kafka-cluster
  ports:
    - port: 9092
      targetPort: 9092
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
#kind: Deployment
metadata:
  name: crs-kafka
spec:
  replicas: 3
  serviceName: kafka-cluster
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      hostname: kafka
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: "1G"
              cpu: "1"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT, LISTENER_LOCAL:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-cluster:9092,LISTENER_LOCAL://localhost:19093
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#              value: crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.default.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.default.svc.cluster.local:2181
              value: "zookeeper-service:2181"