apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-mysql
  template:
    metadata:
      labels:
        app: camel-mysql
    spec:
      containers:
        - name: camel-mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: camel-mysql-srv
spec:
  selector:
    app: camel-mysql
  ports:
    - port: 3306
      targetPort: 3306