apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schema-registry-new
  name: schema-registry-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-new
  template:
    metadata:
      labels:
        app: schema-registry-new
    spec:
      containers:
        - command:
              - bash
              - -c
              - unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schema-registry
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"
            - name: SCHEMA_REGISTRY_HEAP_OPTS
              value: -Xms512M -Xmx2G
            - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
              value: cp-schema-registry
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'kafka-2.kafka.default.svc.cluster.local:29092,kafka-1.kafka.default.svc.cluster.local:29092,kafka-0.kafka.default.svc.cluster.local:29092'
          name: schema-registry
          image: confluentinc/cp-schema-registry:6.0.1
          ports:
            - containerPort: 8081
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    name: schema-registry
spec:
  ports:
    - port: 8081
  selector:
    name: schema-registry-new